### ISSUE TITLE
Django 1.7.7/Python 3.4.0: Invalid syntax

### ISSUE THREAD

**Issue by shamanis** [django-recurrence/django-recurrence#56]
So when you try to run the installation and obtain the following:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/envs/event_system/lib/python3.4/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/home/envs/event_system/lib/python3.4/site-packages/django/core/management/__init__.py", line 354, in execute
    django.setup()
  File "/home/envs/event_system/lib/python3.4/site-packages/django/__init__.py", line 21, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/envs/event_system/lib/python3.4/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/home/envs/event_system/lib/python3.4/site-packages/django/apps/config.py", line 87, in create
    module = import_module(entry)
  File "/home/envs/event_system/lib/python3.4/importlib/__init__.py", line 104, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2231, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2214, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2203, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1448, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/envs/event_system/lib/python3.4/site-packages/recurrence/__init__.py", line 1, in <module>
    from recurrence.base import (
  File "/home/envs/event_system/lib/python3.4/site-packages/recurrence/base.py", line 850
    except exceptions.ValidationError, error:
                                     ^
SyntaxError: invalid syntax

Therefore, the code does not compatible with Python3?

**Comment by shamanis** [comment]
Ouch! Sorry! I'm install version 1.0.0. Reinstall on version 1.2.0 - worked!
